Install-Module MSOnline
Connect-MsolService
Get-MsolAccountSku | select -ExpandProperty ServiceStatus


ServicePlan                                             ProvisioningStatus
-----------                                             ------------------
EXCHANGE_S_FOUNDATION                                   Success
Microsoft Stream                                        Success
OFFICE_PROPLUS_DEVICE                                   Success
INFORMATION_BARRIERS                                    Success
VIVA_LEARNING_SEEDED                                    Success
DYN365_CDS_O365_P1                                      Success
PROJECT_O365_P1                                         Success
EducationAnalyticsP1                                    Success
KAIZALA_O365_P2                                         Success
MICROSOFT_SEARCH                                        Success
WHITEBOARD_PLAN1                                        Success
BPOS_S_TODO_2                                           Success
AAD_BASIC_EDU                                           Success
SCHOOL_DATA_SYNC_P1                                     Success
STREAM_O365_E3                                          Success
TEAMS1                                                  Success
INTUNE_O365                                             PendingActivation
Deskless                                                Success
FLOW_O365_P2                                            Success
POWERAPPS_O365_P2                                       Success
RMS_S_ENTERPRISE                                        Success
OFFICE_FORMS_PLAN_2                                     Success
PROJECTWORKMANAGEMENT                                   Success
SWAY                                                    Success
YAMMER_EDU                                              Success
OFFICESUBSCRIPTION                                      Success
SHAREPOINTWAC_EDU                                       Success
SHAREPOINTSTANDARD_EDU                                  Success
EXCHANGE_S_STANDARD                                     Success
MCOSTANDARD                                             Success
EXCHANGE_S_FOUNDATION                                   Success
SPZA                                                    Success
EXCHANGE_S_FOUNDATION                                   Success
WINDOWS_STORE                                           Success
CDS_CUSTOMER_INSIGHTS_BASE                              Success
DYN365_CUSTOMER_INSIGHTS_ENGAGEMENT_INSIGHTS_BASE_TRIAL Success
Forms_Pro_Customer_Insights                             Success
CDS_CUSTOMER_INSIGHTS_TRIAL                             Success
DYN365_CUSTOMER_INSIGHTS_VIRAL                          Success
INFORMATION_BARRIERS                                    Success
PROJECT_O365_P1                                         Success
DYN365_CDS_O365_P1                                      Success
EducationAnalyticsP1                                    Success
KAIZALA_O365_P2                                         Success
MICROSOFT_SEARCH                                        Success
WHITEBOARD_PLAN1                                        Success
OFFICEMOBILE_SUBSCRIPTION                               Success
BPOS_S_TODO_2                                           Success
AAD_BASIC_EDU                                           Success
SCHOOL_DATA_SYNC_P1                                     Success
STREAM_O365_E3                                          Success
TEAMS1                                                  Success
Deskless                                                Success
FLOW_O365_P2                                            Success
POWERAPPS_O365_P2                                       Success
RMS_S_ENTERPRISE                                        Success
OFFICE_FORMS_PLAN_2                                     Success
PROJECTWORKMANAGEMENT                                   Success
SWAY                                                    Success
INTUNE_O365                                             PendingActivation
YAMMER_EDU                                              Success
SHAREPOINTWAC_EDU                                       Success
MCOSTANDARD                                             Success
SHAREPOINTSTANDARD_EDU                                  Success
EXCHANGE_S_STANDARD                                     Success
Intune_ServiceNow                                       Success
M365_AUDIT_PLATFORM                                     Success
REMOTE_HELP                                             Success
VIVA_LEARNING_SEEDED                                    Success
Nucleus                                                 Success
ContentExplorer_Standard                                Success
WINDOWSUPDATEFORBUSINESS_DEPLOYMENTSERVICE              Success
UNIVERSAL_PRINT_01                                      Success
MICROSOFTENDPOINTDLP                                    Success
MIP_S_Exchange                                          Success
MICROSOFT_COMMUNICATION_COMPLIANCE                      Success
Content_Explorer                                        Success
POWER_VIRTUAL_AGENTS_O365_P3                            Success
CDS_O365_P3                                             Success
PROJECT_O365_P3                                         Success
INSIDER_RISK                                            Success
EXCEL_PREMIUM                                           Success
MTP                                                     Success
DYN365_CDS_O365_P3                                      Success
RECORDS_MANAGEMENT                                      Success
ML_CLASSIFICATION                                       Success
INSIDER_RISK_MANAGEMENT                                 Success
INFO_GOVERNANCE                                         Success
DATA_INVESTIGATIONS                                     Success
CUSTOMER_KEY                                            Success
COMMUNICATIONS_DLP                                      Success
COMMUNICATIONS_COMPLIANCE                               Success
SAFEDOCS                                                Success
M365_ADVANCED_AUDITING                                  Success
MIP_S_CLP1                                              Success
MIP_S_CLP2                                              Success
EducationAnalyticsP1                                    Success
INFORMATION_BARRIERS                                    Success
KAIZALA_STANDALONE                                      Success
MICROSOFT_SEARCH                                        Success
PREMIUM_ENCRYPTION                                      Success
WHITEBOARD_PLAN3                                        Success
PAM_ENTERPRISE                                          Success
ATA                                                     Success
INTUNE_EDU                                              Success
MICROSOFTBOOKINGS                                       Success
BPOS_S_TODO_3                                           Success
MINECRAFT_EDUCATION_EDITION                             Success
Virtualization Rights for Windows 10 (E3/E5+VDA)        Success
ADALLOM_S_STANDALONE                                    Success
RMS_S_PREMIUM2                                          Success
RMS_S_PREMIUM                                           Success
INTUNE_A                                                Success
MFA_PREMIUM                                             Success
AAD_PREMIUM                                             Success
AAD_PREMIUM_P2                                          Success
WINDEFATP                                               Success
LOCKBOX_ENTERPRISE                                      Success
MCOMEETADV                                              Success
MCOEV                                                   Success
BI_AZURE_P2                                             Success
THREAT_INTELLIGENCE                                     Success
EQUIVIO_ANALYTICS                                       Success
EXCHANGE_ANALYTICS                                      Success
ATP_ENTERPRISE                                          Success
AAD_BASIC_EDU                                           Success
STREAM_O365_E5                                          Success
SCHOOL_DATA_SYNC_P2                                     Success
INTUNE_O365                                             PendingActivation
RMS_S_ENTERPRISE                                        Success
TEAMS1                                                  Success
SWAY                                                    Success
Deskless                                                Success
POWERAPPS_O365_P3                                       Success
FLOW_O365_P3                                            Success
OFFICE_FORMS_PLAN_3                                     Success
PROJECTWORKMANAGEMENT                                   Success
YAMMER_EDU                                              Success
MCOSTANDARD                                             Success
SHAREPOINTWAC_EDU                                       Success
SHAREPOINTENTERPRISE_EDU                                Success
EXCHANGE_S_ENTERPRISE                                   Success
ADALLOM_S_O365                                          Success
OFFICESUBSCRIPTION                                      Success
INFORMATION_BARRIERS                                    Success
DYN365_CDS_O365_P1                                      Success
PROJECT_O365_P1                                         Success
EducationAnalyticsP1                                    Success
KAIZALA_O365_P2                                         Success
MICROSOFT_SEARCH                                        Success
WHITEBOARD_PLAN1                                        Success
BPOS_S_TODO_2                                           Success
AAD_BASIC_EDU                                           Success
SCHOOL_DATA_SYNC_P1                                     Success
STREAM_O365_E3                                          Success
TEAMS1                                                  Success
INTUNE_O365                                             PendingActivation
Deskless                                                Success
FLOW_O365_P2                                            Success
POWERAPPS_O365_P2                                       Success
RMS_S_ENTERPRISE                                        Success
OFFICE_FORMS_PLAN_2                                     Success
PROJECTWORKMANAGEMENT                                   Success
SWAY                                                    Success
YAMMER_EDU                                              Success
SHAREPOINTWAC_EDU                                       Success
SHAREPOINTSTANDARD_EDU                                  Success
EXCHANGE_S_STANDARD                                     Success
OFFICESUBSCRIPTION                                      Success
MCOSTANDARD                                             Success
EXCHANGE_S_FOUNDATION                                   Success
DYN365_CDS_VIRAL                                        Success
FLOW_P2_VIRAL                                           Success
FLOW_CCI_BOTS                                           Success
CCIBOTS_PRIVPREV_VIRAL                                  Success
DYN365_CDS_CCI_BOTS                                     Success
FORMS_PRO                                               Success
FORMS_PLAN_E5                                           Success
FLOW_FORMS_PRO                                          Success
EXCHANGE_S_FOUNDATION                                   Success
DYN365_CDS_FORMS_PRO                                    Success
EXCHANGE_S_FOUNDATION                                   Success
FLOW_P2_VIRAL_REAL                                      Success
DYN365_CDS_VIRAL                                        Success
POWERAPPS_P2_VIRAL                                      Success
FLOW_P2_VIRAL                                           Success
EXCHANGE_S_FOUNDATION                                   Success
DYN365_ENTERPRISE_P1_IW                                 Success
WINDEFATP                                               Success
EXCHANGE_S_FOUNDATION                                   Success
Intune_ServiceNow                                       Success
M365_AUDIT_PLATFORM                                     Success
REMOTE_HELP                                             Success
INFORMATION_BARRIERS                                    Success
MICROSOFTBOOKINGS                                       Success
UNIVERSAL_PRINT_NO_SEEDING                              Success
Content_Explorer                                        Success
PROJECT_O365_P3                                         Success
MTP                                                     Success
DYN365_CDS_O365_P3                                      Success
SAFEDOCS                                                Success
MIP_S_CLP1                                              Success
EducationAnalyticsP1                                    Success
KAIZALA_STANDALONE                                      Success
MICROSOFT_SEARCH                                        Success
THREAT_INTELLIGENCE                                     Success
ADALLOM_S_STANDALONE                                    Success
WHITEBOARD_PLAN3                                        Success
ATA                                                     Success
INTUNE_EDU                                              Success
ADALLOM_S_DISCOVERY                                     Success
BPOS_S_TODO_2                                           Success
Virtualization Rights for Windows 10 (E3/E5+VDA)        Success
MINECRAFT_EDUCATION_EDITION                             Success
INTUNE_A                                                Success
MFA_PREMIUM                                             Success
AAD_PREMIUM                                             Success
AAD_PREMIUM_P2                                          Success
STREAM_O365_E3                                          Success
POWERAPPS_O365_P2                                       Success
FLOW_O365_P2                                            Success
OFFICE_FORMS_PLAN_2                                     Success
ATP_ENTERPRISE                                          Success
AAD_BASIC_EDU                                           Success
SCHOOL_DATA_SYNC_P2                                     Success
INTUNE_O365                                             PendingActivation
RMS_S_ENTERPRISE                                        Success
TEAMS1                                                  Success
SWAY                                                    Success
Deskless                                                Success
PROJECTWORKMANAGEMENT                                   Success
YAMMER_EDU                                              Success
MCOSTANDARD                                             Success
SHAREPOINTWAC_EDU                                       Success
SHAREPOINTENTERPRISE_EDU                                Success
EXCHANGE_S_ENTERPRISE                                   Success
ADALLOM_S_O365                                          Success
OFFICESUBSCRIPTION                                      Success
EXCHANGE_S_FOUNDATION                                   Success
DYN365_CDS_DYN_APPS                                     Success
Dynamics_365_Talent_Onboard                             Success
Dynamics_365_Onboarding_Free_PLAN                       Success
EXCHANGE_S_FOUNDATION                                   Success
BI_AZURE_P0                                             Success
MCOPSTNC                                                Success
PROJECT_PROFESSIONAL_FACULTY                            Success
FLOW_FOR_PROJECT                                        Success
DYN365_CDS_PROJECT                                      Success
EXCHANGE_S_FOUNDATION                                   Success
SHAREPOINT_PROJECT_EDU                                  Success
SHAREPOINTENTERPRISE_EDU                                Success
SHAREPOINTWAC_EDU                                       Success
PROJECT_CLIENT_SUBSCRIPTION                             Success
POWER_PAGES_VTRIAL                                      Success
EXCHANGE_S_FOUNDATION                                   Success
DYN365_CDS_VIRAL                                        Success
INFORMATION_BARRIERS                                    Success
VIVA_LEARNING_SEEDED                                    Success
Nucleus                                                 Success
PROJECT_O365_P1                                         Success
DYN365_CDS_O365_P1                                      Success
EducationAnalyticsP1                                    Success
KAIZALA_O365_P2                                         Success
MICROSOFT_SEARCH                                        Success
WHITEBOARD_PLAN1                                        Success
OFFICEMOBILE_SUBSCRIPTION                               Success
BPOS_S_TODO_2                                           Success
AAD_BASIC_EDU                                           Success
SCHOOL_DATA_SYNC_P1                                     Success
STREAM_O365_E3                                          Success
TEAMS1                                                  Success
Deskless                                                Success
FLOW_O365_P2                                            Success
POWERAPPS_O365_P2                                       Success
RMS_S_ENTERPRISE                                        Success
OFFICE_FORMS_PLAN_2                                     Success
PROJECTWORKMANAGEMENT                                   Success
SWAY                                                    Success
INTUNE_O365                                             PendingActivation
YAMMER_EDU                                              Success
SHAREPOINTWAC_EDU                                       Success
MCOSTANDARD                                             Success
SHAREPOINTSTANDARD_EDU                                  Success
EXCHANGE_S_STANDARD                                     Success
EXCHANGE_S_FOUNDATION                                   Success
PROJECT_MADEIRA_PREVIEW_IW                              Success
MCOEV_VIRTUALUSER                                       Success
EXCHANGE_S_FOUNDATION                                   Success
RMS_S_ADHOC                                             Success
EXCHANGE_S_FOUNDATION                                   Success
DYN365_CDS_DEV_VIRAL                                    Success
FLOW_DEV_VIRAL                                          Success
POWERAPPS_DEV_VIRAL                                     Success